"""empty message

Revision ID: 19b206c53298
Revises: 5e1c20427037
Create Date: 2017-09-20 23:07:21.501743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b206c53298'
down_revision = '5e1c20427037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'individual_income',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('customer', 'marital_status',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'marital_status',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('customer', 'individual_income',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
