"""empty message

Revision ID: 1bc190da5811
Revises: a964a2d0e5e0
Create Date: 2018-06-09 20:55:36.037897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc190da5811'
down_revision = 'a964a2d0e5e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('requester_ip', sa.String(), nullable=True))
    op.add_column('transaction', sa.Column('requester_url', sa.String(), nullable=True))
    op.drop_column('transaction', 'request_url')
    op.add_column('transaction_audit', sa.Column('requester_ip', sa.String(), nullable=True))
    op.add_column('transaction_audit', sa.Column('requester_url', sa.String(), nullable=True))
    op.drop_column('transaction_audit', 'request_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_audit', sa.Column('request_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('transaction_audit', 'requester_url')
    op.drop_column('transaction_audit', 'requester_ip')
    op.add_column('transaction', sa.Column('request_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('transaction', 'requester_url')
    op.drop_column('transaction', 'requester_ip')
    # ### end Alembic commands ###
