"""empty message

Revision ID: 2bf3f8c742c5
Revises: 95fb74286bed
Create Date: 2017-09-12 15:52:18.869224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf3f8c742c5'
down_revision = '95fb74286bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('account_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('account_type', sa.String(length=50), nullable=True))
    op.drop_column('user', 'individual_income')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'subscribe')
    op.drop_column('user', 'signature')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'household_income')
    op.drop_column('user', 'marital_status')
    op.drop_column('user', 'dependents')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dependents', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('marital_status', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('household_income', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('signature', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('subscribe', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('individual_income', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user', 'account_type')
    op.drop_column('user', 'account_id')
    # ### end Alembic commands ###
