"""empty message

Revision ID: 356a0effa031
Revises: 70a42b3cc0b6
Create Date: 2017-08-21 10:24:06.583024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356a0effa031'
down_revision = '70a42b3cc0b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dependents', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.Unicode(length=255), nullable=False))
    op.add_column('user', sa.Column('household_income', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('individual_income', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.Unicode(length=255), nullable=False))
    op.add_column('user', sa.Column('marital_status', sa.Integer(), nullable=False))
    op.drop_column('user', 'income')
    op.drop_column('user', 'number_of_dependents')
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstname', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('lastname', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('number_of_dependents', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('income', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user', 'marital_status')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'individual_income')
    op.drop_column('user', 'household_income')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'dependents')
    # ### end Alembic commands ###
