"""empty message

Revision ID: 3bbc3739af98
Revises: 1edd8a5ee0c6
Create Date: 2017-09-17 17:56:23.358046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bbc3739af98'
down_revision = '1edd8a5ee0c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor', sa.Column('company_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor', 'company_name')
    # ### end Alembic commands ###
