"""empty message

Revision ID: 4beab9064488
Revises: 939e2bc19ff9
Create Date: 2017-10-24 18:13:02.003467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4beab9064488'
down_revision = '939e2bc19ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gradient_price', sa.Column('max_price', sa.Integer(), nullable=False))
    op.add_column('gradient_price', sa.Column('min_price', sa.Integer(), nullable=False))
    op.drop_column('gradient_price', 'base_price')
    op.add_column('product', sa.Column('image_url', sa.Unicode(), nullable=True))
    op.add_column('product', sa.Column('max_income', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('min_income', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'name')
    op.drop_column('product', 'min_income')
    op.drop_column('product', 'max_income')
    op.drop_column('product', 'image_url')
    op.add_column('gradient_price', sa.Column('base_price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('gradient_price', 'min_price')
    op.drop_column('gradient_price', 'max_price')
    # ### end Alembic commands ###
