"""empty message

Revision ID: 4ec8d08f5a4f
Revises: b51b88c5edc7
Create Date: 2018-06-16 22:22:42.058085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ec8d08f5a4f'
down_revision = 'b51b88c5edc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.drop_column('customer', 'stripe_id')
    op.add_column('customer_audit', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.drop_column('customer_audit', 'stripe_id')
    op.add_column('transaction', sa.Column('stripe_charge_id', sa.String(), nullable=True))
    op.drop_column('transaction', 'stripe_id')
    op.add_column('transaction_audit', sa.Column('stripe_charge_id', sa.String(), nullable=True))
    op.drop_column('transaction_audit', 'stripe_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_audit', sa.Column('stripe_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('transaction_audit', 'stripe_charge_id')
    op.add_column('transaction', sa.Column('stripe_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('transaction', 'stripe_charge_id')
    op.add_column('customer_audit', sa.Column('stripe_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('customer_audit', 'stripe_customer_id')
    op.add_column('customer', sa.Column('stripe_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('customer', 'stripe_customer_id')
    # ### end Alembic commands ###
