"""empty message

Revision ID: 5674286baf3e
Revises: 356a0effa031
Create Date: 2017-08-21 13:34:38.213253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5674286baf3e'
down_revision = '356a0effa031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('signature', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'signature')
    # ### end Alembic commands ###
