"""empty message

Revision ID: 5bc4840fa214
Revises: 4ec8d08f5a4f
Create Date: 2018-09-08 19:59:34.352702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bc4840fa214'
down_revision = '4ec8d08f5a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor', sa.Column('stripe_is_authorized', sa.Boolean(), nullable=True))
    op.add_column('vendor_audit', sa.Column('stripe_is_authorized', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_audit', 'stripe_is_authorized')
    op.drop_column('vendor', 'stripe_is_authorized')
    # ### end Alembic commands ###
