"""empty message

Revision ID: 5e1c20427037
Revises: 3bbc3739af98
Create Date: 2017-09-18 23:24:47.545603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e1c20427037'
down_revision = '3bbc3739af98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('vendor', 'company_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor', sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('vendor', 'name')
    # ### end Alembic commands ###
