"""empty message

Revision ID: 70a42b3cc0b6
Revises: 0c91c9080de2
Create Date: 2017-08-15 15:29:42.506371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a42b3cc0b6'
down_revision = '0c91c9080de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_status')
    op.add_column('transaction', sa.Column('status', sa.Enum('OPEN', 'SUCCESS', 'FAILURE', name='transactionstatus'), nullable=False))
    op.drop_constraint('transaction_transaction_status_id_fkey', 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'transaction_status_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('transaction_status_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('transaction_transaction_status_id_fkey', 'transaction', 'transaction_status', ['transaction_status_id'], ['id'])
    op.drop_column('transaction', 'status')
    op.create_table('transaction_status',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='transaction_status_pkey'),
    sa.UniqueConstraint('name', name='transaction_status_name_key')
    )
    # ### end Alembic commands ###
