"""empty message

Revision ID: 72790a2cd07f
Revises: f16c69f73b29
Create Date: 2017-09-26 11:49:48.517655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72790a2cd07f'
down_revision = 'f16c69f73b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor', sa.Column('min_income', sa.Integer(), nullable=True))
    op.add_column('vendor', sa.Column('min_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor', 'min_price')
    op.drop_column('vendor', 'min_income')
    # ### end Alembic commands ###
