"""empty message

Revision ID: 7c097c04f393
Revises: caf9188f0905
Create Date: 2017-10-15 20:31:30.928371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c097c04f393'
down_revision = 'caf9188f0905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('vendor_id', sa.Integer(), nullable=False))
    op.alter_column('transaction', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'transaction', 'vendor', ['vendor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.alter_column('transaction', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('transaction', 'vendor_id')
    # ### end Alembic commands ###
