"""empty message

Revision ID: 939e2bc19ff9
Revises: cd5d3080646d
Create Date: 2017-10-21 18:22:16.161305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939e2bc19ff9'
down_revision = 'cd5d3080646d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'first_name')
    op.drop_column('customer', 'last_name')
    op.add_column('user', sa.Column('first_name', sa.Unicode(length=255), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.Unicode(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.add_column('customer', sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('customer', sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
