"""empty message

Revision ID: 94d2c442fe79
Revises: 72790a2cd07f
Create Date: 2017-09-26 12:42:12.279919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d2c442fe79'
down_revision = '72790a2cd07f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor', sa.Column('max_income', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor', 'max_income')
    # ### end Alembic commands ###
