"""empty message

Revision ID: 95fb74286bed
Revises: c480e55ade9f
Create Date: 2017-09-12 13:40:07.355332

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '95fb74286bed'
down_revision = 'c480e55ade9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor', sa.Column('stripe_pk', sqlalchemy_utils.types.encrypted.EncryptedType(), nullable=True))
    op.add_column('vendor', sa.Column('stripe_sk', sqlalchemy_utils.types.encrypted.EncryptedType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor', 'stripe_sk')
    op.drop_column('vendor', 'stripe_pk')
    # ### end Alembic commands ###
