"""empty message

Revision ID: a3a2335c2088
Revises: 12922e1b298c
Create Date: 2018-06-11 20:28:44.075697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3a2335c2088'
down_revision = '12922e1b298c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_source', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('payment_source', sa.Column('stripe_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_payment_source_customer_id'), 'payment_source', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'payment_source', 'customer', ['customer_id'], ['id'])
    op.drop_column('payment_source', 'stripe_src_id')
    op.add_column('transaction', sa.Column('stripe_id', sa.String(), nullable=True))
    op.add_column('transaction_audit', sa.Column('stripe_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_audit', 'stripe_id')
    op.drop_column('transaction', 'stripe_id')
    op.add_column('payment_source', sa.Column('stripe_src_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payment_source', type_='foreignkey')
    op.drop_index(op.f('ix_payment_source_customer_id'), table_name='payment_source')
    op.drop_column('payment_source', 'stripe_id')
    op.drop_column('payment_source', 'customer_id')
    # ### end Alembic commands ###
