"""empty message

Revision ID: a964a2d0e5e0
Revises: f180fde5fe32
Create Date: 2018-06-09 19:43:43.514260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a964a2d0e5e0'
down_revision = 'f180fde5fe32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('request_url', sa.String(), nullable=True))
    op.drop_column('transaction', 'requst_url')
    op.add_column('transaction_audit', sa.Column('request_url', sa.String(), nullable=True))
    op.drop_column('transaction_audit', 'requst_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_audit', sa.Column('requst_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('transaction_audit', 'request_url')
    op.add_column('transaction', sa.Column('requst_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('transaction', 'request_url')
    # ### end Alembic commands ###
