"""empty message

Revision ID: aaacbec1740c
Revises: 19b206c53298
Create Date: 2017-09-24 10:48:27.646051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaacbec1740c'
down_revision = '19b206c53298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transaction_customer_id_fkey', 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key('transaction_customer_id_fkey', 'transaction', 'user', ['customer_id'], ['id'])
    # ### end Alembic commands ###
