"""empty message

Revision ID: b51b88c5edc7
Revises: a3a2335c2088
Create Date: 2018-06-11 20:54:17.289831

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b51b88c5edc7'
down_revision = 'a3a2335c2088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_source')
    op.drop_table('payment_source_audit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_source_audit',
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', postgresql.ENUM('INSERT', 'UPDATE', name='auditaction'), autoincrement=False, nullable=False),
    sa.Column('individual_income', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('household_income', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('marital_status', postgresql.ENUM('NOT_MARRIED', 'MARRIED', name='maritalstatus'), autoincrement=False, nullable=False),
    sa.Column('dependents', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('signature', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stripe_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('timestamp', name='payment_source_audit_pkey')
    )
    op.create_table('payment_source',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stripe_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='payment_source_customer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='payment_source_pkey')
    )
    # ### end Alembic commands ###
