"""empty message

Revision ID: c480e55ade9f
Revises: 74a15d195fb9
Create Date: 2017-09-11 17:43:30.125218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c480e55ade9f'
down_revision = '74a15d195fb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('uuid', postgresql.UUID(), nullable=True))
    op.create_index(op.f('ix_transaction_uuid'), 'transaction', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_uuid'), table_name='transaction')
    op.drop_column('transaction', 'uuid')
    # ### end Alembic commands ###
