"""empty message

Revision ID: caf9188f0905
Revises: d371705de5f2
Create Date: 2017-10-10 16:18:30.564154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf9188f0905'
down_revision = 'd371705de5f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'marital_status',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'marital_status',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
