"""empty message

Revision ID: d371705de5f2
Revises: 94d2c442fe79
Create Date: 2017-10-01 13:23:19.220477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd371705de5f2'
down_revision = '94d2c442fe79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen_at')
    # ### end Alembic commands ###
