"""empty message

Revision ID: eb57f17e2522
Revises: 5674286baf3e
Create Date: 2017-08-28 17:07:52.697834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb57f17e2522'
down_revision = '5674286baf3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subscribe', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'subscribe')
    # ### end Alembic commands ###
