"""empty message

Revision ID: f16c69f73b29
Revises: aaacbec1740c
Create Date: 2017-09-24 11:42:22.054074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f16c69f73b29'
down_revision = 'aaacbec1740c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('stripe_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'stripe_id')
    # ### end Alembic commands ###
