"""empty message

Revision ID: f180fde5fe32
Revises: 143ee3e99967
Create Date: 2018-06-09 19:42:45.289638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f180fde5fe32'
down_revision = '143ee3e99967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('requst_url', sa.String(), nullable=True))
    op.add_column('transaction_audit', sa.Column('requst_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_audit', 'requst_url')
    op.drop_column('transaction', 'requst_url')
    # ### end Alembic commands ###
