"""empty message

Revision ID: f8e883e5b327
Revises: 5e17ef77f31c
Create Date: 2017-10-24 18:21:52.490671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e883e5b327'
down_revision = '5e17ef77f31c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('max_price', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('min_price', sa.Integer(), nullable=True))
    op.drop_column('product', 'min_income')
    op.drop_column('product', 'max_income')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('max_income', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('min_income', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('product', 'min_price')
    op.drop_column('product', 'max_price')
    # ### end Alembic commands ###
